In [110]:
import os
import time
import json
import joblib
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import mlflow
import mlflow.sklearn
from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    StratifiedKFold,
    GridSearchCV
)
from sklearn.compose import ColumnTransformer
from sklearn.datasets import fetch_openml
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import (
    StandardScaler,
    OneHotEncoder
)
from sklearn.model_selection import GridSearchCV

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    ConfusionMatrixDisplay,
    confusion_matrix
)

print("MLflow version:", mlflow.__version__)

MLflow version: 3.16.0

In [111]:
adult = fetch_openml(name="adult", version=2, as_frame=True)

In [112]:
df=adult.frame.copy()

In [113]:
df.shape

(48842, 15)

In [114]:
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [115]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'class'],
      dtype='str')

In [116]:
target = "class"
features = [col for col in df.columns if col != target]

df = df.dropna()
df = df.drop_duplicates()

x = df[features].copy()
y = df[target].copy()

print("Features:", features)
print("X shape:", X.shape)
print("y shape:", y.shape)

Features: ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']
X shape: (48842, 14)
y shape: (45175,)

In [117]:
missing_values=x.isnull().sum()
print("Missing values in each feature:\n", missing_values)

Missing values in each feature:
 age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
dtype: int64

In [118]:
x.dtypes

age                  int64
workclass         category
fnlwgt               int64
education         category
education-num        int64
marital-status    category
occupation        category
relationship      category
race              category
sex               category
capital-gain         int64
capital-loss         int64
hours-per-week       int64
native-country    category
dtype: object

In [119]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42, stratify=y)

In [120]:
numerical_features = x.select_dtypes(include=np.number).columns.tolist()
categorical_features = x.select_dtypes(exclude=np.number).columns.tolist()

print("Numerical features:", numeric_features)
print("Categorical features:", categorical_features)

Numerical features: ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']
Categorical features: ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']

In [121]:
numeric_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

In [122]:
numeric_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

In [123]:
categorical_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),  
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

In [124]:
categorical_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [125]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_pipeline, numerical_features),
        ('cate', categorical_pipeline, categorical_features)
    ]
)

preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'fnlwgt', 'education-num',
                                  'capital-gain', 'capital-loss',
                                  'hours-per-week']),
                                ('cate',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['workclass', 'education', 'marital-status',
                                  'occupation', 'relationship', 'race', 'sex',
                                  'native-country'])])

In [126]:
x_train_preprocessed = preprocessor.fit_transform(x_train)

x_train_preprocessed.shape

(36140, 104)

In [127]:
x_test_transformed = preprocessor.transform(x_test)
x_test_transformed.shape

(9035, 104)

In [128]:
logistic_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000))
])

In [129]:
logistic_pipeline.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'fnlwgt',
                                                   'education-num',
                                                   'capital-gain',
                                                   'capital-loss',
                                                   'hours-per-week']),
                                                 ('cate',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['workclass', 'education',
                                                   'marital-status',
                                                   'occupation', 'relationship',
                                                   'race', 'sex',
                                                   'native-country'])])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [130]:
y_pred = logistic_pipeline.predict(x_test)
y_pred[0:10]

array(['>50K', '>50K', '<=50K', '<=50K', '<=50K', '>50K', '>50K', '<=50K',
       '>50K', '<=50K'], dtype=object)

In [131]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8472606530160487

In [132]:
accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(y_test, y_pred, pos_label='>50K')
recall = recall_score(y_test, y_pred, pos_label='>50K')
f1 = f1_score(y_test, y_pred, pos_label='>50K')

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy: 0.8472606530160487
Precision: 0.7394209354120267
Recall: 0.5928571428571429
F1 Score: 0.6580773042616452

In [133]:
print("Classification Report:\n", classification_report(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

       <=50K       0.87      0.93      0.90      6795
        >50K       0.74      0.59      0.66      2240

    accuracy                           0.85      9035
   macro avg       0.81      0.76      0.78      9035
weighted avg       0.84      0.85      0.84      9035

In [134]:
logistic_pipeline.named_steps['classifier']

LogisticRegression(max_iter=1000)

In [135]:
logistic_pipeline.named_steps['preprocessor']

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'fnlwgt', 'education-num',
                                  'capital-gain', 'capital-loss',
                                  'hours-per-week']),
                                ('cate',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['workclass', 'education', 'marital-status',
                                  'occupation', 'relationship', 'race', 'sex',
                                  'native-country'])])

In [136]:
fitted_pipeline = logistic_pipeline.named_steps[
    'preprocessor']
fitted_num = fitted_pipeline.named_transformers_['num']

fitted_num = fitted_pipeline.named_transformers_['cate']

In [137]:
print(f"fitted_num: {fitted_num.named_steps['imputer'].statistics_}")

fitted_num: ['Private' 'HS-grad' 'Married-civ-spouse' 'Prof-specialty' 'Husband'
 'White' 'Male' 'United-States']

In [138]:
features_names=(logistic_pipeline.named_steps['preprocessor'].get_feature_names_out())
print("Feature Names:", features_names)

Feature Names: ['num__age' 'num__fnlwgt' 'num__education-num' 'num__capital-gain'
 'num__capital-loss' 'num__hours-per-week' 'cate__workclass_Federal-gov'
 'cate__workclass_Local-gov' 'cate__workclass_Private'
 'cate__workclass_Self-emp-inc' 'cate__workclass_Self-emp-not-inc'
 'cate__workclass_State-gov' 'cate__workclass_Without-pay'
 'cate__education_10th' 'cate__education_11th' 'cate__education_12th'
 'cate__education_1st-4th' 'cate__education_5th-6th'
 'cate__education_7th-8th' 'cate__education_9th'
 'cate__education_Assoc-acdm' 'cate__education_Assoc-voc'
 'cate__education_Bachelors' 'cate__education_Doctorate'
 'cate__education_HS-grad' 'cate__education_Masters'
 'cate__education_Preschool' 'cate__education_Prof-school'
 'cate__education_Some-college' 'cate__marital-status_Divorced'
 'cate__marital-status_Married-AF-spouse'
 'cate__marital-status_Married-civ-spouse'
 'cate__marital-status_Married-spouse-absent'
 'cate__marital-status_Never-married' 'cate__marital-status_Separated'
 'cate__marital-status_Widowed' 'cate__occupation_Adm-clerical'
 'cate__occupation_Armed-Forces' 'cate__occupation_Craft-repair'
 'cate__occupation_Exec-managerial' 'cate__occupation_Farming-fishing'
 'cate__occupation_Handlers-cleaners' 'cate__occupation_Machine-op-inspct'
 'cate__occupation_Other-service' 'cate__occupation_Priv-house-serv'
 'cate__occupation_Prof-specialty' 'cate__occupation_Protective-serv'
 'cate__occupation_Sales' 'cate__occupation_Tech-support'
 'cate__occupation_Transport-moving' 'cate__relationship_Husband'
 'cate__relationship_Not-in-family' 'cate__relationship_Other-relative'
 'cate__relationship_Own-child' 'cate__relationship_Unmarried'
 'cate__relationship_Wife' 'cate__race_Amer-Indian-Eskimo'
 'cate__race_Asian-Pac-Islander' 'cate__race_Black' 'cate__race_Other'
 'cate__race_White' 'cate__sex_Female' 'cate__sex_Male'
 'cate__native-country_Cambodia' 'cate__native-country_Canada'
 'cate__native-country_China' 'cate__native-country_Columbia'
 'cate__native-country_Cuba' 'cate__native-country_Dominican-Republic'
 'cate__native-country_Ecuador' 'cate__native-country_El-Salvador'
 'cate__native-country_England' 'cate__native-country_France'
 'cate__native-country_Germany' 'cate__native-country_Greece'
 'cate__native-country_Guatemala' 'cate__native-country_Haiti'
 'cate__native-country_Holand-Netherlands' 'cate__native-country_Honduras'
 'cate__native-country_Hong' 'cate__native-country_Hungary'
 'cate__native-country_India' 'cate__native-country_Iran'
 'cate__native-country_Ireland' 'cate__native-country_Italy'
 'cate__native-country_Jamaica' 'cate__native-country_Japan'
 'cate__native-country_Laos' 'cate__native-country_Mexico'
 'cate__native-country_Nicaragua'
 'cate__native-country_Outlying-US(Guam-USVI-etc)'
 'cate__native-country_Peru' 'cate__native-country_Philippines'
 'cate__native-country_Poland' 'cate__native-country_Portugal'
 'cate__native-country_Puerto-Rico' 'cate__native-country_Scotland'
 'cate__native-country_South' 'cate__native-country_Taiwan'
 'cate__native-country_Thailand' 'cate__native-country_Trinadad&Tobago'
 'cate__native-country_United-States' 'cate__native-country_Vietnam'
 'cate__native-country_Yugoslavia']

In [139]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(logistic_pipeline, x, y, cv=cv, scoring='f1')
print("Cross-Validation F1 Scores:", cv_scores)
print("Mean Cross-Validation F1 Score:", cv_scores.mean())
print("Mean Cross-Validation F1 Score:", cv_scores.std())

c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_scorer.py", line 174, in __call__
    score = scorer._score(
        cached_call, estimator, *args, **routed_params.get(name).score
    )
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
        estimator,
    ...<2 lines>...
        pos_label=pos_label,
    )
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ~~~~~~~~~~~~~~~~~~~~^
        estimator, *args, response_method=response_method, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
    ...<2 lines>...
    )
ValueError: pos_label=1 is not a valid label: It should be one of ['<=50K' '>50K']

  warnings.warn(
c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_scorer.py", line 174, in __call__
    score = scorer._score(
        cached_call, estimator, *args, **routed_params.get(name).score
    )
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
        estimator,
    ...<2 lines>...
        pos_label=pos_label,
    )
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ~~~~~~~~~~~~~~~~~~~~^
        estimator, *args, response_method=response_method, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
    ...<2 lines>...
    )
ValueError: pos_label=1 is not a valid label: It should be one of ['<=50K' '>50K']

  warnings.warn(
c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_scorer.py", line 174, in __call__
    score = scorer._score(
        cached_call, estimator, *args, **routed_params.get(name).score
    )
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
        estimator,
    ...<2 lines>...
        pos_label=pos_label,
    )
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ~~~~~~~~~~~~~~~~~~~~^
        estimator, *args, response_method=response_method, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
    ...<2 lines>...
    )
ValueError: pos_label=1 is not a valid label: It should be one of ['<=50K' '>50K']

  warnings.warn(
c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_scorer.py", line 174, in __call__
    score = scorer._score(
        cached_call, estimator, *args, **routed_params.get(name).score
    )
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
        estimator,
    ...<2 lines>...
        pos_label=pos_label,
    )
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ~~~~~~~~~~~~~~~~~~~~^
        estimator, *args, response_method=response_method, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
    ...<2 lines>...
    )
ValueError: pos_label=1 is not a valid label: It should be one of ['<=50K' '>50K']

  warnings.warn(

Cross-Validation F1 Scores: [nan nan nan nan nan]
Mean Cross-Validation F1 Score: nan
Mean Cross-Validation F1 Score: nan

c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\model_selection\_validation.py:978: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_scorer.py", line 174, in __call__
    score = scorer._score(
        cached_call, estimator, *args, **routed_params.get(name).score
    )
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_scorer.py", line 461, in _score
    y_pred = method_caller(
        estimator,
    ...<2 lines>...
        pos_label=pos_label,
    )
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_scorer.py", line 97, in _cached_call
    result, _ = _get_response_values(
                ~~~~~~~~~~~~~~~~~~~~^
        estimator, *args, response_method=response_method, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Engineer Omar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\_response.py", line 208, in _get_response_values
    raise ValueError(
    ...<2 lines>...
    )
ValueError: pos_label=1 is not a valid label: It should be one of ['<=50K' '>50K']

  warnings.warn(

In [140]:
param_grid = {
    'classifier__C': [0.01, 0.1, 1, 10, 100],
}

grid_search = GridSearchCV(
    estimator=logistic_pipeline,
    param_grid=param_grid,
    cv=5,
    n_jobs=-1
)

grid_search.fit(x_train, y_train)

print("Best Parameters:", grid_search.best_params_)
print(f"Best score: {grid_search.best_score_}")

Best Parameters: {'classifier__C': 1}
Best score: 0.8477310459324847

In [141]:
best_pipeline = grid_search.best_estimator_

predictions = best_pipeline.predict(x_test)

print("classification_report:\n", classification_report(y_test, predictions))

classification_report:
               precision    recall  f1-score   support

       <=50K       0.87      0.93      0.90      6795
        >50K       0.74      0.59      0.66      2240

    accuracy                           0.85      9035
   macro avg       0.81      0.76      0.78      9035
weighted avg       0.84      0.85      0.84      9035

In [142]:
logistic_pipeline.get_params().keys()

dict_keys(['memory', 'steps', 'transform_input', 'verbose', 'preprocessor', 'classifier', 'preprocessor__n_jobs', 'preprocessor__remainder', 'preprocessor__sparse_threshold', 'preprocessor__transformer_weights', 'preprocessor__transformers', 'preprocessor__verbose', 'preprocessor__verbose_feature_names_out', 'preprocessor__num', 'preprocessor__cate', 'preprocessor__num__memory', 'preprocessor__num__steps', 'preprocessor__num__transform_input', 'preprocessor__num__verbose', 'preprocessor__num__imputer', 'preprocessor__num__scaler', 'preprocessor__num__imputer__add_indicator', 'preprocessor__num__imputer__copy', 'preprocessor__num__imputer__fill_value', 'preprocessor__num__imputer__keep_empty_features', 'preprocessor__num__imputer__missing_values', 'preprocessor__num__imputer__strategy', 'preprocessor__num__scaler__copy', 'preprocessor__num__scaler__with_mean', 'preprocessor__num__scaler__with_std', 'preprocessor__cate__memory', 'preprocessor__cate__steps', 'preprocessor__cate__transform_input', 'preprocessor__cate__verbose', 'preprocessor__cate__imputer', 'preprocessor__cate__onehot', 'preprocessor__cate__imputer__add_indicator', 'preprocessor__cate__imputer__copy', 'preprocessor__cate__imputer__fill_value', 'preprocessor__cate__imputer__keep_empty_features', 'preprocessor__cate__imputer__missing_values', 'preprocessor__cate__imputer__strategy', 'preprocessor__cate__onehot__categories', 'preprocessor__cate__onehot__drop', 'preprocessor__cate__onehot__dtype', 'preprocessor__cate__onehot__feature_name_combiner', 'preprocessor__cate__onehot__handle_unknown', 'preprocessor__cate__onehot__max_categories', 'preprocessor__cate__onehot__min_frequency', 'preprocessor__cate__onehot__sparse_output', 'classifier__C', 'classifier__class_weight', 'classifier__dual', 'classifier__fit_intercept', 'classifier__intercept_scaling', 'classifier__l1_ratio', 'classifier__max_iter', 'classifier__n_jobs', 'classifier__penalty', 'classifier__random_state', 'classifier__solver', 'classifier__tol', 'classifier__verbose', 'classifier__warm_start'])

In [143]:
combined_param_grid = {
    "preprocessor__num__imputer__strategy": ["median", "mean"],
    "classifier__C":[0.1, 1, 10]
    
}

combined_search = GridSearchCV(
    estimator=logistic_pipeline,
    param_grid=combined_param_grid,
    cv=5,
    n_jobs=-1
)

combined_search.fit(x_train, y_train)

print("Best Parameters:", combined_search.best_params_)
print(f"Best score: {combined_search.best_score_}")

Best Parameters: {'classifier__C': 1, 'preprocessor__num__imputer__strategy': 'median'}
Best score: 0.8477310459324847

In [144]:
models_canditates = {
    "LogisticRegression": LogisticRegression(max_iter=1000),
    "RandomForestClassifier": RandomForestClassifier(
        n_estimators=100,
        random_state=42,
        max_depth=5
    )
}

results = []

for model_name, estimator in models_canditates.items():
    pipeline = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('classifier', estimator)
    ])
    
    cv_scores = cross_val_score(
        pipeline,
        x,
        y,
        cv=cv,
        scoring='f1_macro'
    )
    
    results.append({
        'model': model_name,
        'mean_f1': cv_scores.mean(),
        'std_f1': cv_scores.std()
    })

results_df = pd.DataFrame(results)

results_df

                    model   mean_f1    std_f1
0      LogisticRegression  0.783765  0.003235
1  RandomForestClassifier  0.730869  0.006556

In [145]:
final_pipeline = combined_search.best_estimator_

joblib.dump(final_pipeline, 'adult_income_pipeline.joblib')

print("Final pipeline saved as 'adult_income_pipeline.joblib'")

Final pipeline saved as 'adult_income_pipeline.joblib'

In [146]:
loaded_pipeline = joblib.load('adult_income_pipeline.joblib')

print("Loaded pipeline from 'adult_income_pipeline.joblib'")

Loaded pipeline from 'adult_income_pipeline.joblib'

In [147]:
loaded_pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'fnlwgt',
                                                   'education-num',
                                                   'capital-gain',
                                                   'capital-loss',
                                                   'hours-per-week']),
                                                 ('cate',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['workclass', 'education',
                                                   'marital-status',
                                                   'occupation', 'relationship',
                                                   'race', 'sex',
                                                   'native-country'])])),
                ('classifier', LogisticRegression(C=1, max_iter=1000))])

In [148]:
new_data = pd.DataFrame({
    'age': [25, 45, 30],
    'workclass': ['Private', 'Private', 'Self-emp-not-inc'],
    'fnlwgt': [226802, 150000, 180000],
    'education': ['11th', 'Bachelors', 'Masters'],
    'education-num': [7, 13, 14],
    'marital-status': ['Never-married', 'Married-civ-spouse', 'Married-civ-spouse'],
    'occupation': ['Machine-op-inspct', 'Exec-managerial', 'Prof-specialty'],
    'relationship': ['Own-child', 'Husband', 'Husband'],
    'race': ['Black', 'White', 'White'],
    'sex': ['Male', 'Male', 'Male'],
    'capital-gain': [0, 0, 0],
    'capital-loss': [0, 0, 0],
    'hours-per-week': [40, 50, 45],
    'native-country': ['United-States', 'United-States', 'United-States']
})

In [149]:
new_data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States
1,45,Private,150000,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States
2,30,Self-emp-not-inc,180000,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,45,United-States

In [150]:
new_predictions = loaded_pipeline.predict(new_data)

print("Predictions for new data:", new_predictions)

new_data

Predictions for new data: ['<=50K' '>50K' '>50K']

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States
1,45,Private,150000,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States
2,30,Self-emp-not-inc,180000,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,45,United-States

In [151]:
unusable_data = pd.DataFrame({
    'age': [25, None],
    'workclass': ['Private', 'Unknown'],
    'fnlwgt': [226802, None],
    'education': ['11th', 'Unknown'],
    'education-num': [7, None],
    'marital-status': ['Never-married', None],
    'occupation': ['Machine-op-inspct', 'Unknown'],
    'relationship': ['Own-child', None],
    'race': ['Black', 'Unknown'],
    'sex': ['Male', 'Unknown'],
    'capital-gain': [0, None],
    'capital-loss': [0, None],
    'hours-per-week': [40, None],
    'native-country': ['United-States', 'Unknown']
})

In [152]:
predictions_unusable = loaded_pipeline.predict(unusable_data)

print("Predictions for unusable data:", predictions_unusable)

Predictions for unusable data: ['<=50K' '<=50K']

In [162]:
results_df

                    model   mean_f1    std_f1
0      LogisticRegression  0.783765  0.003235
1  RandomForestClassifier  0.730869  0.006556

In [154]:
from sklearn.metrics import f1_score

y_test_pred = best_pipeline.predict(x_test)

test_f1 = f1_score(y_test, y_test_pred, pos_label='>50K')

print("Test F1:", test_f1)

Test F1: 0.6580773042616452

### **Part M — Conclusion**


The **Logistic Regression pipeline** was the best configuration, achieving the highest cross-validation F1-score.

1. **Best pipeline configuration:** Logistic Regression with the applied preprocessing steps.
2. **Cross-validation F1-score:** **0.78** (Std = **0.00323**).
3. **Test F1-score:** **0.6581**.
4. **Why save the complete pipeline?** Saving the complete pipeline is safer because it includes both the preprocessing steps and the trained model. This guarantees that new data is transformed in the same way as the training data and helps prevent preprocessing inconsistencies and prediction errors.

In [155]:
mlflow.set_tracking_uri("sqlite:///mlruns.db")
mlflow.set_experiment("Adult_Census_Pipeline")

<Experiment: artifact_location='file:d:/ml/mlflow_git_pipeline/mlruns/1', creation_time=1791400826495, effective_trace_archival_retention=None, experiment_id='1', last_update_time=1791400826495, lifecycle_stage='active', name='Adult_Census_Pipeline', tags={}, trace_location=None, workspace='default'>

In [156]:
with mlflow.start_run():

    C = 1.0
    max_iter = 1000

    model = LogisticRegression(
        C=C,
        max_iter=max_iter
    )

    mlflow.log_param("C", C)
    mlflow.log_param("max_iter", max_iter)

    # Log metrics
    mlflow.log_metric("accuracy", accuracy)
    mlflow.log_metric("precision", precision)
    mlflow.log_metric("recall", recall)
    mlflow.log_metric("f1_score", f1)

    print("Run completed.")
    print("Accuracy:", accuracy)
    print("F1:", f1)

Run completed.
Accuracy: 0.8472606530160487
F1: 0.6580773042616452

In [160]:
with mlflow.start_run(run_name="RandomForest_Demo"):

    rf_pipeline = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('classifier', RandomForestClassifier(
            n_estimators=100,
            random_state=42
        ))
    ])

    # Train
    rf_pipeline.fit(x_train, y_train)

    # Predict
    y_pred = rf_pipeline.predict(x_test)

    # Metrics
    accuracy_rf = accuracy_score(y_test, y_pred)
    precision_rf = precision_score(y_test, y_pred, pos_label='>50K')
    recall_rf = recall_score(y_test, y_pred, pos_label='>50K')
    f1_rf = f1_score(y_test, y_pred, pos_label='>50K')

    # Parameters
    mlflow.log_param("n_estimators", 100)
    mlflow.log_param("random_state", 42)

    # Metrics
    mlflow.log_metric("accuracy", accuracy_rf)
    mlflow.log_metric("precision", precision_rf)
    mlflow.log_metric("recall", recall_rf)
    mlflow.log_metric("f1", f1_rf)

    # Tags
    mlflow.set_tag("algorithm", "RandomForest")
    mlflow.set_tag("dataset", "adult_census")
    mlflow.set_tag("developer", "Omar Elshnofy")

    # Log complete pipeline
    mlflow.sklearn.log_model(
        sk_model=rf_pipeline,
        name="model",
        skops_trusted_types=["numpy.dtype"]
    )

    print("Accuracy =", accuracy_rf)
    print("Precision =", precision_rf)
    print("Recall =", recall_rf)
    print("F1 Score =", f1_rf)

Accuracy = 0.8509131156613171
Precision = 0.7407008086253369
Recall = 0.6133928571428572
F1 Score = 0.671062271062271

In [161]:
runs = mlflow.search_runs(
    experiment_names=["Adult_Census_Pipeline"]
)

runs[[
    "run_id",
    "tags.mlflow.runName",
    "status",
    "metrics.f1"
]]

,run_id,tags.mlflow.runName,status,metrics.f1
0,e1d7ae4ee46c48e89747a8eac34b68d4,RandomForest_Demo,FINISHED,0.671062
1,b4ddbe0b68324af9a4b0e3b6c093b033,RandomForest_Demo,FAILED,NaN
2,c562831e335c4f0eba8ece9fee04d023,RandomForest_Demo,FAILED,NaN
3,d43eefb7c3494bad8bb605eca6cbf2c1,suave-sow-359,FINISHED,NaN
4,b9c0d461f6be4761a248ba46e88fa921,languid-dolphin-111,FINISHED,NaN
5,9e3009d217ef4efb83aecf32533c88e4,inquisitive-hawk-527,FINISHED,NaN
6,5110c11cd4204c3d923a497748eb9e43,caring-dog-909,FAILED,NaN
7,6b750fd7254343e898108be20b6b4c45,puzzled-ox-847,FAILED,NaN
8,f300128c44c14fb28e934d840d3fff60,"Grid_{'classifier__C': 10, 'classifier__solver...",FINISHED,NaN
9,318fa0c04e954607b3a2608515da0587,"Grid_{'classifier__C': 10, 'classifier__solver...",FINISHED,NaN
10,a6578b072c1e43f18983472b79d9b23b,"Grid_{'classifier__C': 1, 'classifier__solver'...",FINISHED,NaN
11,4fbe79f0cba74e29a3627873ba28397e,"Grid_{'classifier__C': 1, 'classifier__solver'...",FINISHED,NaN
12,86796ac84e48475d8c8398ca28038a5a,"Grid_{'classifier__C': 0.1, 'classifier__solve...",FINISHED,NaN
13,133b45102c5a43bc9d4a9bb9136c024d,"Grid_{'classifier__C': 0.1, 'classifier__solve...",FINISHED,NaN
14,7cfc62cd9a60487ea8c5d792ac8886fb,Part_I_GridSearch_Parent,FINISHED,NaN
15,a41a6258480e4a64b9f016a75ef86adb,Part_I_GridSearch_Parent,FAILED,NaN
16,07ba574e68854cfdaf01db77f813dc96,Part_F_LogisticRegression,FINISHED,0.567937
17,fa15b1a952e04f5cb90102f664cddcbd,LogisticRegression,FINISHED,NaN
18,bc892712fbcf4f3a8516ec5c7f13eb39,LogisticRegression,FAILED,NaN